# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "intel_8080"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disassembler"
path = "src/disassembler/main.rs"

[dependencies]
